image: docker:24.0.5

services:
  - docker:24.0.5-dind

variables:
  DOCKER_TLS_CERTDIR: "/certs"

stages:
  - build_and_test

build_and_test:
  stage: build_and_test
  before_script:
    - apk add --no-cache curl docker-cli-compose
    - cp .env.example .env
  script:
    - echo "Starting Docker Compose Build..."
    - docker compose up -d --build
    - echo "Waiting for Laravel to initialize inside app container..."
    - echo "Menunggu proses Laravel install, NPM build, dan FrankenPHP siap (bisa memakan waktu 2-3 menit)..."
    - |
      timeout_count=0
      # Melakukan ping setiap 10 detik, maksimal 24 kali (240 detik / 4 menit)
      while ! curl -f -s -o /dev/null http://docker:8000 && ! curl -f -s -o /dev/null http://localhost:8000; do
        timeout_count=$((timeout_count+1))
        if [ $timeout_count -ge 24 ]; then
          echo "Waktu habis! Server tidak menyala."
          docker compose logs
          exit 1
        fi
        echo "Menunggu server menyala... ($timeout_count/24)"
        sleep 10
      done
    - echo "Testing Application UI / HTTP Response... Sukses!"
